sudo: false

rvm:
  - 1.9.3
  - 2.2.6
  - 2.3.3

gemfile:
gemfile:
  - gemfiles/mysql_ar_32.gemfile
  - gemfiles/mysql_ar_40.gemfile
  - gemfiles/mysql_ar_41.gemfile
  - gemfiles/mysql_ar_42.gemfile
  - gemfiles/mysql2_ar_50.gemfile
  - gemfiles/pg_ar_32.gemfile
  - gemfiles/pg_ar_40.gemfile
  - gemfiles/pg_ar_41.gemfile
  - gemfiles/pg_ar_42.gemfile
  - gemfiles/pg_ar_50.gemfile
  - gemfiles/sqlite3_ar_32.gemfile
  - gemfiles/sqlite3_ar_40.gemfile
  - gemfiles/sqlite3_ar_41.gemfile
  - gemfiles/sqlite3_ar_42.gemfile
  - gemfiles/sqlite3_ar_50.gemfile

matrix:
  exclude:
    - rvm: 1.9.3
      gemfile: gemfiles/mysql_ar_41.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/pg_ar_41.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/sqlite3_ar_41.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/mysql_ar_42.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/pg_ar_42.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/sqlite3_ar_42.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/mysql2_ar_50.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/pg_ar_50.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/sqlite3_ar_50.gemfile
    - rvm: 2.2.6
      gemfile: gemfiles/mysql_ar_32.gemfile
    - rvm: 2.2.6
      gemfile: gemfiles/pg_ar_32.gemfile
    - rvm: 2.2.6
      gemfile: gemfiles/sqlite3_ar_32.gemfile
    - rvm: 2.3.3
      gemfile: gemfiles/mysql_ar_32.gemfile
    - rvm: 2.3.3
      gemfile: gemfiles/pg_ar_32.gemfile
    - rvm: 2.3.3
      gemfile: gemfiles/sqlite3_ar_32.gemfile

services:
  - mysql
  - postgresql

before_script:
  - mysql -e 'create database ancestry_test;' || true
  - psql -c 'create database ancestry_test;' -U postgres || true
